### ISSUE TITLE
Active sub-page navigation style.

### ISSUE THREAD

**Issue by tombstone-10** [tombstone-10/Automita#13]
Dear Team Members,
**Request to you:**

The tab section which is opened should have a similar active like in sidebar, previously it had the active class as we were using NavLink (but that adds class in virtual dom and makes difficult to manipulate state). Therefore I replaced NavLink with Link for tabs.jsx component only. We need to find a solution where we can know what sub page is active and add active css class to it. 

Thank you,
Ali Ahmed

![image](https://github.com/tombstone-10/Automita/assets/77021315/3a3563c3-5778-4d12-8311-635947b1754b)

**Comment by umee007** [comment]
There are multiple ways to solve this problem. Some common ways are: 
1):- We can add .active class and add styling to all the link buttons separately.

2):- Get full URL (window.location) , parse it to get what section the end user is viewing and then add dynamic styling to that link

**Comment by tombstone-10** [comment]
Dear Team Members @umee007 @J-tahir 

I will be working and finding a solution to this as Umar is working on the other issue.

Thank you!

**Comment by J-tahir** [comment]
Ok that's great. Let me know if you need me.

**Comment by tombstone-10** [comment]
issue resolved, added an additional page for profile as it helped resolving this issue. will be a simple page with some text "lets get started" and some list.
