### ISSUE TITLE
Data sending from Login to App

### ISSUE THREAD

**Issue by tombstone-10** [tombstone-10/Automita#14]
Dear Team Members,
Request to you:

In order to render dashboard, we need to know if login is successful and for that we need to get that value in App.jsx as that is where Dashboard component is. As we will be implementing conditional rendering so we do need to get value from child and pass it to parent.

I tried using context API but according to my knowledge it cannot be used to send data from child to parent. Therefore the solution logic I have chosen is a callback function.

Do suggest me a better approach if there is so we can implement that.

Thank you,
Ali Ahmed

**Comment by umee007** [comment]
1) Declare state in parent component and pass (setState) to child as a prop. Then we can change the state in child and access it in parent 

2) According to my knowledge, use context can handle this situation only if we make a custom use context hook (i.e use context in separate files)

**Comment by tombstone-10** [comment]
> 1) Declare state in parent component and pass (setState) to child as a prop. Then we can change the state in child and access it in parent 
> 
> 2) According to my knowledge, use context can handle this situation only if we make a custom use context hook (i.e use context in separate files)

The second one seems interesting, I will definitely try it and if it works then it is a better preference.

Thank you, excellent work!

**Comment by umee007** [comment]
Dear Team, please let me handle this situation. As there are some logics in my mind, i want to test them all.

**Comment by tombstone-10** [comment]
> Dear Team, please let me handle this situation. As there are some logics in my mind, i want to test them all. 

That is perfect, go ahead. Just remember to commit into server-side branch as it all yours. But remember if you make any mistake and push on server branch, you may have no backup so do make local backup.

Once you are done setting up the logic, arrange a meeting with me so we can push it into test branch and see for issues during pull-request.

Also I will be creating a new task (just for information), the task related a successful login and showing user's information on dashboard. 

Thank you,
Ali Ahmed

**Comment by tombstone-10** [comment]
Amazing work, solved through custom hook which is not passing data from child to parent component but accessing the state in child and getting the value. Tested and closing it.
